"""
scanner.py — The scan orchestrator. Runs all 5 modules in parallel.

Change from the old version:
  BEFORE: imported save_scan from app.storage.scan_store (JSON files)
  AFTER:  imports save_scan from app.database.db_store   (PostgreSQL)
          also accepts a `db: AsyncSession` parameter passed in from
          the background task in routes.py.

Why pass the session in rather than creating one here?
  The background task already owns a session for its entire lifetime.
  Sharing that session means every DB operation in one scan is part of
  the same connection — efficient and consistent.
"""

import asyncio
import uuid
from datetime import datetime

from sqlalchemy.ext.asyncio import AsyncSession

from app.database.db_store import save_scan
from app.models.result import ScanResult
from app.models.scan import ScanMeta
from app.services.dns_service import run_dns
from app.services.headers_service import run_headers
from app.services.ssl_service import run_ssl
from app.services.subdomain_service import run_subdomains
from app.services.whois_service import run_whois


async def run_scan(
    domain: str,
    scan_id: str | None = None,
    db: AsyncSession | None = None,
) -> ScanResult:
    """
    Main scan orchestrator.

    scan_id — the UUID generated by routes.py before the background task
              starts. Passing it in keeps the ID consistent between the
              initial "running" row and the final "complete" row.

    db      — the AsyncSession from the background task. If somehow called
              without one (e.g. from tests or CLI), we raise early so the
              bug is obvious rather than silent.

    asyncio.gather() — runs all 5 module coroutines at the SAME TIME.
    Like assigning 5 researchers to work on 5 topics simultaneously instead
    of one after another. The scan finishes as fast as the slowest module,
    not the sum of all modules.

    _safe_run() wraps each module: if WHOIS crashes, DNS still completes.
    Partial results always beat a total failure.

    save_scan() is called twice:
      1. Before gather() → writes the "running" row (already done by routes.py,
         this call updates it with the meta we've built here — idempotent)
      2. After gather()  → updates to "complete" with full results
    """
    if db is None:
        raise RuntimeError(
            "run_scan() requires a database session. "
            "Pass db=session from the background task."
        )

    scan_id = scan_id or str(uuid.uuid4())
    started_at = datetime.utcnow()

    meta = ScanMeta(
        id=scan_id,
        domain=domain,
        started_at=started_at,
        status="running",
    )

    async def _safe_run(coro, module_name: str):
        """
        Wraps any module coroutine in a try/except.
        Returns None on failure so one broken module never stops the rest.

        coro        — a coroutine object (an async function that hasn't
                      been awaited yet). We await it here inside the wrapper.
        module_name — just for the log message so we know which one failed.
        """
        try:
            return await coro
        except Exception as e:
            print(f"[scanner] {module_name} failed: {e}")
            return None

    print(f"[scanner] Starting scan {scan_id} for {domain}")

    # asyncio.gather() — the powerhouse.
    # Fires all 5 coroutines concurrently and waits until ALL finish.
    # Each result comes back in the same order we listed them — even if
    # subdomain discovery finishes last, its result is still the 5th item.
    (
        whois_result,
        dns_result,
        ssl_result,
        headers_result,
        subdomains_result,
    ) = await asyncio.gather(
        _safe_run(run_whois(domain),      "WHOIS"),
        _safe_run(run_dns(domain),        "DNS"),
        _safe_run(run_ssl(domain),        "SSL"),
        _safe_run(run_headers(domain),    "Headers"),
        _safe_run(run_subdomains(domain), "Subdomains"),
    )

    completed_at = datetime.utcnow()
    duration_ms = int((completed_at - started_at).total_seconds() * 1000)

    meta.completed_at = completed_at
    meta.duration_ms  = duration_ms
    meta.status       = "complete"

    result = ScanResult(
        meta       = meta,
        whois      = whois_result,
        dns        = dns_result,
        ssl        = ssl_result,
        headers    = headers_result,
        subdomains = subdomains_result,
    )

    # save_scan() detects the row already exists (written by routes.py as
    # "running") and updates it with the completed data. One row per scan, always.
    await save_scan(result, db)
    print(f"[scanner] Scan {scan_id} complete in {duration_ms}ms")
    return result
